language: java
sudo: false
jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew
   

after_success:
#- ./gradlew test jacocoTestReport coveralls
- ./gradlew cobertura coveralls

after_failure:
- ./gradlew clean check --debug